# Generated by Django 6.0 on 2025-12-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(help_text='Каждый ингредиент с новой строки', verbose_name='Ингредиенты')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления (минуты)')),
                ('difficulty', models.CharField(choices=[('легко', 'Легко'), ('средне', 'Средне'), ('сложно', 'Сложно')], default='средне', max_length=50, verbose_name='Сложность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-created_at'],
            },
        ),
    ]
